### ISSUE TITLE
sending any character via .sendLetter?

### ISSUE THREAD

**Issue by yegor211** [garimpeiro-it/node-key-sender#12]
Hi! I'm trying to send different characters with no success. For example: "आ". How can I make the lib send this symbol? Sorry if this is a stupid question, but I tried a lot of stuff and it didn't help. Looking forward for your help!

**Comment by fernandohu** [comment]
Hi! How do you type this character using your physical keyboard? If you use multiple keys, you may need a combination or sending multiple keys for that.

For example. 

- Uppercase 'A' is the combination of two keycodes: SHIFT + A.

- Letter 'A' with accent 'Ã' is made by sending two keycodes: first by pressing '~' followed by another key press 'A'.
