### ISSUE TITLE
require('node-key-sender') return undefined in node red

### ISSUE THREAD

**Issue by natachasanquer** [garimpeiro-it/node-key-sender#13]
Hi, I'm trying to use node-key-sender in node-red. 
I use the functionGlobalContext like this : 
` functionGlobalContext: {
		...,
		robot:require('node-key-sender')
    }`
But when I do : 
`var robot = global.get('robot');

node.log(robot);`

It returns Undefined.

I've already done : npm install and the package 'node-key-sender' does exist at ~/.node-red/node_modules

Can anyone help please ?

**Comment by fernandohu** [comment]
Hello, I've installed node-red to my machine but since it is a new framework to me, I have no idea what to do to reproduce your problem. Can you provide more details so I can reproduce it?
