### ISSUE TITLE
node-key-sender not installing

### ISSUE THREAD

**Issue by orbyog** [garimpeiro-it/node-key-sender#14]
Sorry if I'm just thick but I have tried installing this but it won't show any new node in the palette.
Tried:
~/.node-red $ npm install --save-dev node-key-sender
~/.node-red $ npm install -g --save-dev node-key-sender
~/.node-red $ npm i -g node-key-sender
~/.node-red $ npm i node-key-sender
~/.node-red $ sudo npm install --save-dev node-key-sender
~/.node-red $ sudo npm install -g --save-dev node-key-sender
~/.node-red $ sudo npm i node-key-sender
~/.node-red $ sudo npm i -g node-key-sender
But doesn't appear in node-red palette.
Any advice would be appreciated.
Robert
should have mentioned on fresh pi3 install with everything updated

**Comment by fernandohu** [comment]
Hi there. I never used the node-red framework, but I do have a Raspberry Pi here with me. I can help you if you provide me some steps to reproduce the problem (consider that I have no knowledge about node-red).

**Comment by orbyog** [comment]
Thank you for your reply. Maybe I am looking at this all wrong. I thought this would add a node for use in node-red ... my bad.
I installed node-red-contrib-sendkeys which states this is a dependency so I assumed it would create another node, I guess that's not the case.
https://www.npmjs.com/package/node-red-contrib-sendkeys?activeTab=readme
