### ISSUE TITLE
Works in development mode, but not on production in electron

### ISSUE THREAD

**Issue by ChaosRambo** [garimpeiro-it/node-key-sender#16]
Hey,
I have the problem, that node-key-sender still works, if electron starts in production mode.
But if I package Electron and install my Electron App, node-key-sender stops to work :(

In my case, I throw ctrl + c on a selected text

`const ks = require('node-key-sender');`
`...`
`ks.sendCombination(['control', 'c']);`

Thanks for your help! :)

**Comment by fernandohu** [comment]
Hello, node-key-sender requires that the running platform has Java run time installed. Also, you have to make sure you copy the jar file (key-sender.jar) in your build process.

**Comment by ChaosRambo** [comment]
Hey,
I know that node-key-sender requires JRE, node-key-sender works fine, but only in production mode...

But if I package my electron app with electron-builder for Linux, Mac or Windows and start the packaged version node-key-sender doesn't work anymore......

**Comment by ChaosRambo** [comment]
Hey,
I've found the problem \o/

If I package my Electron App, Electron compressed all files to an *.asar file inclusive any node module.... 

Therefore, node-key-sender can't find the jar file....

Electron-Builder has the feature to unpack files from the *.asar file so I can unpack this module an and the node-key-sender works in production mode \o/

Thanks for your help :)

**Comment by ChaosRambo** [comment]
Ohh sry, I need to disable asar completely!

**Comment by josephj** [comment]
Oh I got exactly the same issue. Thanks for pointing out
