### ISSUE TITLE
Single quotes around JAR file stops the jar file from running

### ISSUE THREAD

**Issue by cmrichards** [garimpeiro-it/node-key-sender#18]
I get his error when I try to run my javascript in Windows 10:

> Error: Command failed: java -jar 'C:\Users\chris\Downloads\key-sender-master\key-sender-master\node_modules\node-key-sender\jar\key-sender.jar' a b c
> Error: Unable to access jarfile 'C:\Users\chris\Downloads\key-sender-master\key-sender-master\node_modules\node-key-sender\jar\key-sender.jar'

The jar file does exist.  If I run this from the command line then I get the exact same message.

If I remove the single quotes around the jar file or replace them with double-quotes, then it works fine:

> java -jar "C:\Users\chris\Downloads\key-sender-master\key-sender-master\node_modules\node-key-sender\jar\key-sender.jar"

The fix is easy, but I'm just curios why no-one has seen this issue before in Windows.

**Comment by NasskalteJuni** [comment]
Same problem & solution for windows here...

**Comment by fernandohu** [comment]
Hello, I have published a new version just now that fixed this problem. Thanks.
