### ISSUE TITLE
To use the "java" command-line tool you need to install a JDK

### ISSUE THREAD

**Issue by bruno-robert** [garimpeiro-it/node-key-sender#29]
I'm trying to get node-key-sender running in an electron project. Every time I use node-key-sender I get a popup with 'To use the "java" command-line tool you need to install a JDK'.

I've followed the "More info..." button that brings me to java.com. I've downloaded Java 8 on the website but I still have to popup.

I've found this website: https://www.theitsage.com/fix-java-command-line-tool-popup-mac/
that talks about this issue, but the package they recommend is to download JRE 6 for old depreciated applications. Does node-key-sender really use this (It says on in the README that the minimum version is 8)?

**Comment by bruno-robert** [comment]
It's seems that even typing "java" in the terminal and running will trigger the popup. I think it's something to do with the JRE not supporting command line tools any more....

Just wondering if there are any other ways or running the .jar file?

P.S.

OS: MacOS Catalina

**Comment by bruno-robert** [comment]
Ok, so downloading the JDK from https://www.oracle.com/technetwork/java/javase/downloads/index.html solves the issue. It's a shame you have to install the whole JDK just to run this though. 

Unfortunately, this opens a "java app" that takes the focus away from any other app. Any keypresses are lost unless the user spam clicks the mouse on the window that should receive the key presses.

**Comment by joeybaba** [comment]
thanks
