### ISSUE TITLE
Node-key-sender doesn't work after build

### ISSUE THREAD

**Issue by gingerbeard-hnly** [garimpeiro-it/node-key-sender#34]
Hi,

During testing, Node-Key-Sender works great but as soon as I build the app it doesn't work.

Error:
Uncaught (in promise) Error: Command failed: java -jar "C:\Users\<username>\github\<appname>\dist\win-unpacked\resources\app.asar\node_modules\node-key-sender\jar\key-sender.jar" windows-shift-s

Any assistance in resolving this issue would be great.

**Comment by Grijan** [comment]
May i know how you got this working, i think we have to bundle (bring in JRE) to the application. But i am not sure how to do it

**Comment by gokul-3** [comment]
> Hi,
> 
> During testing, Node-Key-Sender works great but as soon as I build the app it doesn't work.
> 
> Error: Uncaught (in promise) Error: Command failed: java -jar "C:\Users<username>\github<appname>\dist\win-unpacked\resources\app.asar\node_modules\node-key-sender\jar\key-sender.jar" windows-shift-s
> 
> Any assistance in resolving this issue would be great.

May I know how to resolve this issue. I am struck in this.

**Comment by gokul-3** [comment]
> May i know how you got this working, i think we have to bundle (bring in JRE) to the application. But i am not sure how to do it

I have included key-sender.jar file in build. but it doesn't work for me. It throws error.

[electron] (java:35173): Gtk-WARNING **: 11:08:35.394: Unable to locate theme engine in module_path: "adwaita",
[electron] 
[electron] (java:35173): Gtk-WARNING **: 11:08:35.394: Unable to locate theme engine in module_path: "pixmap",
[electron] 
[electron] (java:35173): Gtk-WARNING **: 11:08:35.395: Unable to locate theme engine in module_path: "pixmap",
[electron] 
[electron] (java:35173): Gtk-WARNING **: 11:08:35.395: Unable to locate theme engine in module_path: "pixmap",
[electron] 
[electron] (java:35173): Gtk-WARNING **: 11:08:35.395: Unable to locate theme engine in module_path: "pixmap",
[electron] 
[electron] (java:35173): Gtk-WARNING **: 11:08:35.395: Unable to locate theme engine in module_path: "pixmap",
[electron] 
[electron] (java:35173): Gtk-WARNING **: 11:08:35.395: Unable to locate theme engine in module_path: "pixmap",
[electron] 
[electron] (java:35173): Gtk-WARNING **: 11:08:35.395: Unable to locate theme engine in module_path: "pixmap",
[electron] 
[electron] (java:35173): Gtk-WARNING **: 11:08:35.395: Unable to locate theme engine in module_path: "pixmap",
[electron] 
[electron] (java:35173): Gtk-WARNING **: 11:08:35.395: Unable to locate theme engine in module_path: "pixmap",
[electron] 
[electron] (java:35173): Gtk-WARNING **: 11:08:35.395: Unable to locate theme engine in module_path: "pixmap",
[electron] 
[electron] (java:35173): Gtk-WARNING **: 11:08:35.395: Unable to locate theme engine in module_path: "pixmap",
[electron] 
[electron] (java:35173): Gtk-WARNING **: 11:08:35.395: Unable to locate theme engine in module_path: "pixmap",
[electron] 
[electron] (java:35173): Gtk-WARNING **: 11:08:35.396: Unable to locate theme engine in module_path: "pixmap",
[electron] 
[electron] (java:35173): Gtk-WARNING **: 11:08:35.396: Unable to locate theme engine in module_path: "pixmap",
[electron] 
[electron] (java:35173): Gtk-WARNING **: 11:08:35.396: Unable to locate theme engine in module_path: "pixmap",
[electron] 
[electron] (java:35173): Gtk-WARNING **: 11:08:35.396: Unable to locate theme engine in module_path: "pixmap",
[electron] 
[electron] (java:35173): Gtk-WARNING **: 11:08:35.396: Unable to locate theme engine in module_path: "pixmap",
[electron] 
[electron] (java:35173): Gtk-WARNING **: 11:08:35.396: Unable to locate theme engine in module_path: "pixmap",
[electron] 
[electron] (java:35173): Gtk-WARNING **: 11:08:35.396: Unable to locate theme engine in module_path: "pixmap",
[electron] 
[electron] (java:35173): Gtk-WARNING **: 11:08:35.397: Unable to locate theme engine in module_path: "pixmap",
[electron] 
[electron] (java:35173): Gtk-WARNING **: 11:08:35.398: Unable to locate theme engine in module_path: "adwaita",
[electron] java: symbol lookup error: /snap/core20/current/lib/x86_64-linux-gnu/libpthread.so.0: undefined symbol: __libc_pthread_init, version GLIBC_PRIVATE

**Comment by Grijan** [comment]
One thing i discovered late is that you need to have `java` installed in your machine, where you are running the app after building, I found this at a later stage. And it looks like you are using ubuntu to build the app right?

**Comment by gokul-3** [comment]
> One thing i discovered late is that you need to have `java` installed in your machine, where you are running the app after building, I found this at a later stage. And it looks like you are using ubuntu to build the app right?

Yes, I'm using ubuntu. I have installed java.

$java -version
openjdk version "11.0.21" 2023-10-17
OpenJDK Runtime Environment (build 11.0.21+9-post-Ubuntu-0ubuntu122.04)
OpenJDK 64-Bit Server VM (build 11.0.21+9-post-Ubuntu-0ubuntu122.04, mixed mode, sharing)

**Comment by Grijan** [comment]
So to confirm what you are saying, you are able to run the application from your dev environment via `CLI` but the same is `NOT` working if the applicaiton is packed in the dev environment. 
Let's hope the above is correct.
So now we need to see the code that you are calling to send the keys, both for the local dev environment and production.

**Comment by gokul-3** [comment]
> So to confirm what you are saying, you are able to run the application from your dev environment via `CLI` but the same is `NOT` working if the applicaiton is packed in the dev environment. Let's hope the above is correct. So now we need to see the code that you are calling to send the keys, both for the local dev environment and production.

the above error is occured because I ran the application in vs code terminal, so it is unable to locate the library

I implemented node-key-sender as below in production.

```
async function callThrowJar(key, jarPath) {
    return new Promise(async (resolve, reject) => {
        exec('java -jar key-sender.jar ' + key, { cwd: jarPath }, (error, out) => {
            if (error) {
                reject(error);
            }
            resolve();
        }, error => {
            console.log('Throw Keys Error -> ' + error);
        });
    });
}
```

but It throws the error

Error : spawn /bin/sh ENOENT

**Comment by Grijan** [comment]
does the word e-con system ring a bell? :)

**Comment by gokul-3** [comment]
> does the word e-con system ring a bell? :)

What do you mean by e-con system?

**Comment by Grijan** [comment]
Please diregard the above message, let me check the code and get back to you

**Comment by Grijan** [comment]
Can you double check if you have java installed in your machine. Try the command java -version from the place where you are running the app and at the same time have a try catch and log the error in a file
