### ISSUE TITLE
Thank you awesome plugin! But found a little problem

### ISSUE THREAD

**Issue by arenacheck** [garimpeiro-it/node-key-sender#4]
Hey first off all thank you for this script it´s the only thing that worked for me and I can now press keys on windows while using node.js <3 Thank you so much!

But if your folder structure is as example C:\xampp\htdocs\sample test\start.js

It will not work because of the space at **sample test**
However no big deal :) But maybe you can fix it in the future

**Comment by amiraslanaslani** [comment]
This problem has been resolved on #3
